name: Electron Builder Action
author: Samuel Meuli, Michael Zarach
description: GitHub Action for building and releasing Electron apps

inputs:
  github_token:
    description: GitHub authentication token
    required: true

  release:
    description: Whether the app should be released after a successful build
    required: false
    default: "false"

  mac_certs:
    description: Base64-encoded code signing certificate for macOS
    required: false
  mac_certs_password:
    description: Password for decrypting `mac_certs`
    required: false

  windows_certs:
    description: Base64-encoded code signing certificate for Windows
    required: false
  windows_certs_password:
    description: Password for decrypting `windows_certs`
    required: false

runs:
  using: node12 # Versions available: https://github.com/actions/node-versions/blob/main/versions-manifest.json
  main: index.js

branding:
  icon: upload-cloud
  color: blue
