## Based on https://github.com/samuelmeuli/mini-diary/blob/master/.github/workflows/release.yml
name: Build & release

# This workflow runs for dev, master branches when a new git tag is created
# and the tag is a version number, like "v1.0.0"

# Suggested workflow:
# Create Git tags like "v1.0.0" on origin/master
# Create Git tags like "v1.0.0-beta.1" or "v1.0.0-alpha.1" for origin/dev

# It will always codesign, notarize, and attempt to publish artifacts to a draft release
on:
  push:
    branches: [master, dev, ci]
    tags:
      - 'v*.*.*' # Only watch for new v- Git tags

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest] # The operating systems to build for
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # https://yarnpkg.com/features/release-workflow#commit-history

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2 # See: https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node }}

      # ----- Yarn Install and Caching ------
      # Cache Yarn 2
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
      # ----- End Yarn Install and Caching ------

      - name: Build/release Electron app
        uses: ./.github/actions/action-electron-builder
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          # type: string
          github_token: ${{ secrets.github_token }}

          # Set release to true when a v- tag is pushed
          # If the commit is tagged with a version (e.g. "v1.0.0")
          # then create a Github release
          # type: boolean
          # See `github.ref`: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Mac certificate info
          mac_certs: ${{ secrets.CSC_LINK }}
          mac_certs_password: ${{ secrets.CSC_KEY_PASSWORD }}
        env:
          # macOS notarization
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          # Workaround for electron-builder error about existing file in CI
          # https://github.com/electron-userland/electron-builder/issues/3179
          USE_HARD_LINKS: false
